### ISSUE TITLE
Possible bug with the confidence interval feature

### ISSUE THREAD

**Issue by tanzimhoque** [ltratt/multitime#11] opened 2015-04-20 17:15 UTC
After running multitime with -c 95, the confidence interval result seems odd?

```
         Mean                Std.Dev.    Min         Median      Max
```

 real        289.409+/-988.4848    9.596       240.783     290.874     296.314
 user        287.989+/-904.7777    9.181       240.263     290.186     293.038
 sys         0.637+/-9.5890      0.945       0.028       0.108       3.028

**Comment by snim2** [comment] 2015-04-20 17:36
Many thanks for reporting this @tanzimhoque - I think it is a duplicate of #9 so I'll close this and move the discussion there, if you don't mind.

**Closed as completed by snim2** 2015-04-20 17:36 UTC
Labels: bug, duplicate
